version: '3.9'

networks:
  default:
    external:
        name: stockTicker

services:
  stocktickerrazorpages:
    image: ${DOCKER_REGISTRY-}stocktickerrazorpages
    container_name: stocktickerrazorpages
    build:
      context: .
      dockerfile: StockTickerRazorPages/Dockerfile
    depends_on: 
        - stocktickerapi
    ports:
        - 5000:80
        - 5001:443

  stocktickerapi:
    image: ${DOCKER_REGISTRY-}stocktickerapi
    container_name: stocktickerapi
    build:
      context: .
      dockerfile: StockTickerApi/Dockerfile
    ports:
        - 5002:80
        - 5003:443

